### ISSUE TITLE
Feature suggestion: impl<T: Validate> Validate for &T

### ISSUE THREAD

**Issue by LucasPickering** [Keats/validator#101]
It would be nice to have `Validate` implemented for any `&T` if it's implemented for `&T`. Since only a reference is needed for validation anyway, it would make it a little more convient to validate non-Copy types. I can't implement this in my own crate because of the orphan rule. I don't _think_ this would cause any breaking changes, but I'm not quite sure. This would obviously be very easy to write so if it's desirable, I'd be happy to put up a PR with it.

**Comment by Keats** [comment]
Please do a PR!
