### ISSUE TITLE
How to validate function parameters or do validation at any places?

### ISSUE THREAD

**Issue by someniceone** [Keats/validator#106]
All the examples have showed how to validate struct properties, but how can we validate function parameters by calling a method, or do validation at any places? Appreciate it!

**Comment by Keats** [comment]
This library only works on structs

**Comment by kevinzheng** [comment]
@Keats 
Do I have any method to validate the parameter `repo_id`? Thank you!
```rust
#[get("/repositories/{repo_id}/files/readFile")]
pub async fn read_file(
    repo_id: web::Path<String>,
    input: web::Query<ReadFileInput>,
) -> Result<HttpResponse, AppError> {
    // How to validate parameter repo_id? 
    input.validate()?;
}
```

**Comment by Keats** [comment]
You can import the validator lib manually but not more than that
