### ISSUE TITLE
Support fancy-regex

### ISSUE THREAD

**Issue by ctopher7** [Keats/validator#108]
Hi, would you please support fancy-regex crate? Because the default regex crate does not want to support look around regex. Thanks

**Comment by Keats** [comment]
I believe it should already work?

**Comment by ctopher7** [comment]
@Keats thank you for your response. Unfortunately, I got error message from Validate macro saying :
```
cannot apply unary operator `!` to type `std::result::Result<bool, fancy_regex::error::Error>`
```

**Comment by ctopher7** [comment]
My bad, I am still using rust 1.21

**Comment by ctopher7** [comment]
Hi @Keats , I know whats wrong. For fancy regex, it needs to be unwrapped one more time because fancy-regex produce Result<bool,fancy_regex::Error> , not straight bool. I ended up create a new function using custom validator

```
use lazy_static::lazy_static;
use fancy_regex::{Regex as FancyRegex};
use validator::ValidationError;

lazy_static! {
    static ref PASSWORD: FancyRegex = FancyRegex::new(r#"^(?=.{6,30})(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*()_+=/\-|\\{}\[\]\:\;\"\',.<>?`~]).*$"#).unwrap();
}

pub fn validate_password(password:&str)-> Result<(), ValidationError>{
    assert!(PASSWORD.is_match(password).unwrap());
    Ok(())
}
```

hope it helps anyone who got this error message
