### ISSUE TITLE
Extract serialisation errors?

### ISSUE THREAD

**Issue by Keats** [Keats/validator#11]
So we can represent them consistently with validation error

**Comment by logankaser** [comment]
It would also be incredible if the validation errors could be serialized so a front end can parse and display them.

**Comment by bradleyess** [comment]
@Keats - can you provide an update on this. I agree with @logankaser that this would be a useful feature.

**Comment by Keats** [comment]
The validation errors can already be serialized.
Extracting the serialisation errors, I don't know if that's possible.
