### ISSUE TITLE
Validate should use absolute type names and not rely on an external import

### ISSUE THREAD

**Issue by bikeshedder** [Keats/validator#112]
The following code does not compile unless I also add `use validator::Validate` beforehand.

```rust
#[derive(
    Clone,
    Debug,
    Eq,
    PartialEq,
    :: serde :: Serialize,
    :: serde :: Deserialize,
    :: validator_derive :: Validate,
)]
pub struct Message {
    #[validate(length(min = 1i64, max = 2048i64))]
    pub text: String,
}
```

This should not be necessary if `::validator_derive::Validate` did use absolute type names. I'm using `validator_derive` as part of generated code and therefore don't want `Validate` to become a reserved name.

Is there a way to change the generated code to use only absolute type names and not depend on `use validator::Validate`?

**Comment by Keats** [comment]
@ELD do you know if that's possible?

**Comment by ELD** [comment]
Yes, this should be possible. Basically, we'll need to replace all references to types with absolute paths. Probably can have a PR cooked up in the next day or two resolving this.

**Comment by bikeshedder** [comment]
Thanks a lot. 👍
