### ISSUE TITLE
'derive' feature does not seem to work for me

### ISSUE THREAD

**Issue by lgmys** [Keats/validator#115]
Hey, thanks for the awesome crate! For some reason, on rust 1.46 the ```derive``` feature did not work for me on the latest version here and I had to go back to 0.10. If someone else confirms this, I can dive into fixing this.

**Comment by Keats** [comment]
cc @ELD 
What's the issue you're getting?

**Comment by ELD** [comment]
Would you please provide a minimal example of your attempted usage including the Rust source and your `Cargo.toml` file?

**Comment by lgmys** [comment]
Case dismissed; this must have been some kind of cache issue as it works just fine now. Forgive me:)
