### ISSUE TITLE
Adding more explanation for features on cargo.toml

### ISSUE THREAD

**Issue by omofolarin** [Keats/validator#120]
Thanks for the good work you are doing with this library. I find it very useful.

Please I encountered issues adding phone verification from the validator_derive crate.

I read the phone section again and again till I tried this. 

```
validator = {version = "0.11", features = ["derive", "phone", "unic", "card"]}
validator_derive = {version = "0.11.0", features = ["unic", "card", "phone"]}
```

Apparently, adding the feature to just validator_derive doesn't get it to work. I spent hours trying to figure this out. Please can you update the readme to this note.

Thanks!!!

**Comment by Keats** [comment]
If you use the `derive` feature, you shouldn't have the `validator_derive` line

**Comment by omofolarin** [comment]
@Keats Thanks for the feedback. I have updated my codebase to this regard.

**Comment by Keats** [comment]
I've updated the README! Thanks for reporting it
