### ISSUE TITLE
Dependent Data

### ISSUE THREAD

**Issue by shiftrtech** [Keats/validator#125]
Hi, i am starting using this nice library but i can't find a way to make a struct field dependent of value of another field.

I want make a field requiered if an Optional field its filled, can you please give some guide on make this, thanks.

**Comment by xFrednet** [comment]
Hey @shiftrtech, I think this is currently only possible by writing your own validation function and adding it to the struct. I found this example in the [test files](https://github.com/Keats/validator/blob/f6a6dddb8bcba27bc772ffa2767136977e91f2d3/validator_derive/tests/complex.rs#L15) and simplified it a bit: 

```rust
fn validate_signup(data: &SignupData) -> Result<(), ValidationError> {
    if data.mail.ends_with("gmail.com") && data.age == 18 {
        return Err(ValidationError::new("stupid_rule"));
    }

    Ok(())
}

#[derive(Debug, Validate, Deserialize)]
#[validate(schema(function = "validate_signup", skip_on_field_errors = false))]
struct SignupData {
    #[validate(email)]
    mail: String,
    #[validate(range(min = 18, max = 20))]
    age: u32,
}
```

**Comment by Keats** [comment]
Yep, what @xFrednet said. No way to make dependent validation right now and it's probably not planned
