### ISSUE TITLE
Option to not set param value?

### ISSUE THREAD

**Issue by prscoelho** [Keats/validator#129]
What do you think about an option to not set param value for a field? The use case would be for password validation. The issue is that a password validation fail might end up in debug logs with the param value set and the password in plain text.

**Comment by Keats** [comment]
I think this would be better handled by the user, since passwords or PHI would be the only target (I think) and you wouldn't log those payloads anyway?

**Comment by prscoelho** [comment]
I guess it is kinda fringe and in retrospect maybe more specific to tide than validator. In my case, with tide, returning early with data.validate()?; and downcasting the error in a middleware (as per tide's [examples](https://github.com/http-rs/tide/blob/main/examples/error_handling.rs)), the error ends up being automatically logged before getting to the error middleware. My solution was to map the error to my own error type and that's fine.

Closing.
