### ISSUE TITLE
Define a comparison type for `must_match` validation

### ISSUE THREAD

**Issue by xFrednet** [Keats/validator#130]
I got this idea while working on #7. It might be cool to define a comparison type for the validation. We could have something like this:

```rust
#[derive(Debug, Validate)]
struct SomeStruct {
    value1: i32,
    #[validate(must_match(other = "value1", eq_type = "i64"))]
    value2: i64
}
```

This would basically be equivalent of doing:
```rust
let a: eq_type = value1.into();
let b: eq_type = value2.into();
validate_must_match(a, b);
```

This can be super useful if we have just different types like `i32` and `i64`. But it might be even cooler to add specific validation like this:
```rust
struct Cake(u64, u32);

#[derive(Eq, PartialEq, Debug)]
struct Food(u64);
impl From<Cake> for Food {
    fn from(cake: Cake) -> Self {
        Food(cake.0)
    }
}

#[derive(Debug, Validate)]
struct SomeStruct {
    value1: Cake,
    #[validate(must_match(other = "value1", eq_type = "Food"))]
    value2: Cake
}
```
This example only compares the first value of `Cake` without caring about the second `u32` one. We could easily define another struct to only compare the second one.

I can try to implement it but I first wanted to get some feedback on the idea. :)

**Comment by Keats** [comment]
I think it's adding too much complexity to the validator lib when it could be handled easily via a custom validation function

**Comment by xFrednet** [comment]
I think that this Synatx is more readable than writing a custom validator that basically does the same and that is would be simple to implement.

I get your point that this would add some complexity to the validator for maybe no real reason. I would suggest that we wait to see if someone finds a valid use case for this :)
