### ISSUE TITLE
Validate Country

### ISSUE THREAD

**Issue by omid** [Keats/validator#138]
Is it possible to have it?
or in another word, can I develop this and create a PR for that?

ref: https://en.wikipedia.org/wiki/List_of_countries_by_population_(United_Nations)

**Comment by omid** [comment]
The problem here is that, in what language?
Maybe we can stick to English only?

I'm sure we do not support phone numbers and credit cards in other numeric systems also.

**Comment by xFrednet** [comment]
What would you exactly validate as a county?

If you just want to validate that a string matches the name of a country you could simply use regex or what would probably be a bit cleaner use the custom validator with a function that does a simple dictionary check. Would that cover your request? 🙃

**Comment by omid** [comment]
Sure I can have a custom validator.
I want to contribute this to the library, to have a better library as the result.

Based on this standard, the validator can support, country name, alpha2 or alpha3.
https://en.wikipedia.org/wiki/ISO_3166-1#Current_codes

**Comment by Keats** [comment]
I don't think it's common enough to be included in the main library

**Comment by omid** [comment]
Thanks
