### ISSUE TITLE
Serializable validations

### ISSUE THREAD

**Issue by lholden** [Keats/validator#14]
It would be nice if the Validate trait could provide access to the validations used on a struct. (Ex, a hashmap of Vecs of Validator.) 

Give the Validator enum Serialize and now you can serialize it to json and pass it to a front end app to share validations. :D

**Comment by Keats** [comment]
yeah, that's actually something I thought of after a conversation on reddit but somehow never created an issue for, thanks for that!

**Comment by incker** [comment]
You can make a struct named `RespErrors` give it a serialize macro and collect errors there.
Example and my code that I use to wrap errors (code can be better):



    use std::borrow::Cow;
    use std::string::ToString;
    
    use validator::{Validate, ValidationErrors, ValidationErrorsKind};
    
    #[derive(Debug, Serialize, Deserialize)]
    pub struct RespErrors {
        pub errors: Vec<(String, String)>,
    }
    
    impl RespErrors {
        pub fn new(errors: Vec<(String, String)>) -> Self {
            RespErrors { errors }
        }
    
        pub fn new_error(error: (String, String)) -> Self {
            RespErrors { errors: vec![error] }
        }
    }
    
    pub trait ValidateFormatter {
        fn run_validator(&self) -> Result<(), RespErrors>;
    }
    
    impl<T> ValidateFormatter for T where T: Validate {
        fn run_validator(&self) -> Result<(), RespErrors> {
            use std::collections::HashMap;
    
            self.validate().map_err(|err: ValidationErrors| {
                let errors: HashMap<&str, validator::ValidationErrorsKind> = err.into_errors();
                let mut err_entries = Vec::with_capacity(errors.len());
    
                for (field, err) in errors {
                    match err {
                        ValidationErrorsKind::Field(vec) => {
                            for msg in vec {
                                let message = msg.message.map(|err_text| err_text.to_string())
                                    .unwrap_or("field input is invalid".to_string());
    
                                let camel_field_name = snake_to_camel_case(field)
                                    .expect(&format!("Invalid snake field: {}", field))
                                    .to_string();
    
    
                                err_entries.push((camel_field_name, message));
                                // one error per field is enough
                                break;
                            }
                        }
                        _ => panic!("Some other type was given"),
                    }
                }
                RespErrors { errors: err_entries }
            })
        }
    }
    
    
    pub fn snake_to_camel_case(snake: &str) -> Result<Cow<str>, ()> {
        if snake.contains("_") {
            if snake.starts_with("_") {
                Err(())
            } else if snake.ends_with("_") {
                Err(())
            } else {
                let mut camel = "".to_string();
                for word in snake.split('_') {
                    if &camel == "" {
                        camel.push_str(word);
                    } else {
                        let (first, rest) = word.split_at(1);
                        camel.push_str(&first.to_uppercase());
                        camel.push_str(rest);
                    }
                }
                Ok(Cow::Owned(camel))
            }
        } else {
            Ok(Cow::Borrowed(snake))
        }
    }
    

The usage is something like this: `my_struct.run_validator()` instead of usual `my_struct.validate()`
