### ISSUE TITLE
Validate email

### ISSUE THREAD

**Issue by Belanchuk** [Keats/validator#144]
https://github.com/Keats/validator/blob/9628aae39c75468fbacfb63bbe1af125dc40bb92/validator/src/validation/email.rs#L102

It is necessary to matching with false.

**Comment by Belanchuk** [comment]
Pull request sent.

**Comment by simanacci** [comment]
I was about to open the same issue. Are there use cases where abc@bar is a valid email?
```rust
    fn main() {
        use validator::Validate;
        #[derive(Debug, Validate)]
        struct TestStruct {
            #[validate(email)]
            val: String,
        }
    
        let s = TestStruct {
            val: "bob@gmail".to_string(),
        };

        assert!(s.validate().is_ok());
    }
```

**Comment by Belanchuk** [comment]
> **Update**: Turns out tld less email addresses are valid -> https://www.netmeister.org/blog/email.html I was about to open the same issue. Are there use cases where abc@bar is a valid email? I'm testing user sign ups and foo@foo is accepted as valid.
> 
> ```rust
>     fn main() {
>         use validator::Validate;
>         #[derive(Debug, Validate)]
>         struct TestStruct {
>             #[validate(email)]
>             val: String,
>         }
>     
>         let s = TestStruct {
>             val: "bob@gmail".to_string(),
>         };
> 
>         assert!(s.validate().is_ok());
>     }
> ```

@Keats thinks it's a valid email address

**Comment by Keats** [comment]
Can someone do a PR?
