### ISSUE TITLE
Derive: mismatched types

### ISSUE THREAD

**Issue by MaxNazarov93** [Keats/validator#150]
Hi! I have an error in compile:
```
#[derive(Deserialize, Validate)]
|                                 ^^^^^^^^
|                                  |
|                                  expected struct `std::string::String`, found `&std::string::String`
|                                  help: try using a conversion method: `(Validate).to_string()`
|                                  in this macro invocation

pub fn derive_validation(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
----------------------------------------------------------------------------------- in this expansion of `#[derive(Validate)]`
```

rustc -V
```
rustc 1.53.0-nightly (07e0e2ec2 2021-03-24)
```

Cargo.toml
```
validator = { version = "0.12.0", features = ["derive"] }
```

I have been tried 0.13 and received same error

**Comment by Keats** [comment]
Can you try with Rust 1.51 to see if it's an issue with nightly?

**Comment by MaxNazarov93** [comment]
Unfortunately, same error

Cargo.toml
`[package]
name = "test-validator"
version = "0.1.0"
authors = ["Maksim Nazarov <sin90gradus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
validator = { version = "0.12.0", features = ["derive"] }`

main.rs
`
use validator::{Validate, ValidationError};

#[derive(Validate)]
pub struct Create {
    #[validate(custom = "validate_name")]
    pub name: String,
}

impl Create {
    fn new(name: String) -> Self{
        return Self{name}
    }
}

fn validate_name(name: String) -> Result<(), ValidationError> {
    match name.as_str() {
        "a" => Ok(()),
        _ => Err(ValidationError::new("name")),
    }
}

fn main() {
    let create = Create::new("b".to_string());
    create.validate();
}
`

rustc -V
`
rustc 1.51.0 (2fd73fabe 2021-03-23)
`

cargo -V
`
cargo 1.51.0 (43b129a20 2021-03-16)
`

**Comment by Keats** [comment]
I don't know if that's the reason but the custom fn should be:
```
fn validate_name(name: &str) -> Result<(), ValidationError> {
    match name.as_str() {
        "a" => Ok(()),
        _ => Err(ValidationError::new("name")),
    }
}
```
Otherwise it would try to move the field

**Comment by MaxNazarov93** [comment]
Yes! Now it's working! Thank you!
Strange compile error confused me, sorry about that
