### ISSUE TITLE
errors returned by custom validators can't specify their own value parameter

### ISSUE THREAD

**Issue by raffomania** [Keats/validator#157]
I have the following custom validator:
```rust
/// A custom password validator that does not leak the password in the error it returns.
pub fn validate_password(password: &String) -> Result<(), ValidationError> {
    let is_valid = validator::validate_length(password, Some(10), Some(100), None);
    if is_valid {
        return Ok(());
    }

    let mut error = ValidationError::new("length");
    error.add_param("value".into(), &"");
    error.add_param("max".into(), &100);
    error.add_param("min".into(), &10);

    Err(error)
}
```

I would expect the error returned by `validate()` to contain an empty string as a value. However, the error contains the actual password.

I can provide a PR containing a test for reproduction if you like, however I'm not sure how to fix the problem itself :)

**Comment by Keats** [comment]
2 things there:

1. validator should not set `value` if it exists (a `if` around https://github.com/Keats/validator/blob/ad820fa6297cf58a70b0940b78bc0855bf5ee065/validator_derive/src/quoting.rs#L183 basically)
2. there should be a `sensitive` (bad name, makes me think of case sensitivity) attribute so we insert `Value::Null` if that's the case so this workaround is not needed in the first place

**Comment by Keats** [comment]
Of course I was pointing to the wrong one >_> 

https://github.com/Keats/validator/blob/ad820fa6297cf58a70b0940b78bc0855bf5ee065/validator_derive/src/quoting.rs#L388

> A new attribute for annotating password fields

Passwords is only one of many, it's also needed for PHI

**Comment by raffomania** [comment]
That looks good, I think I could try to whip up a PR with a new attribute for marking security-sensitive fields. Would you be interested in that?

**Comment by raffomania** [comment]
Ideas:

- `secret`
- `security_sensitive`
- `dont_expose_value`

**Comment by mdtusz** [comment]
I'd keep it simple with just `sensitive = true` as a "meta" parameter, similar to `message = "foo"` and `code` parameters.

If someone can point me in the right direction on this, I'd be happy to make a PR.

**Comment by mdtusz** [comment]
I seem to have it implemented mostly - will open a PR later today or tomorrow. Just need to sort out how to make it such that it will work with the presence of `sensitve` and not require `sensitive = true` explicitly (if possible).

**Comment by Keats** [comment]
Ok in practice I think the value should not be passed at all so closing this issue and the current value will be removed in a future version.
