### ISSUE TITLE
Port to macros 1.1

### ISSUE THREAD

**Issue by theduke** [Keats/validator#16]
Thanks for the awesome work, love this crate.

With macros 1.1 now becoming stable, do you have any plans to port this over?

That would allow use on stable!

**Comment by Keats** [comment]
It should work on stable after 1.15 automatically as it uses macro 1.1! 
If something needs to change to have it working, i'll do it asap but it should already work

**Comment by Keats** [comment]
And thanks for the kind words!

**Comment by theduke** [comment]
Oh, I got a compiler warning about custom_derive, but that was apparently due to another crate.

**Comment by Keats** [comment]
No worries, happens to everyone

If you have time, I'd love feedback on https://github.com/Keats/validator/issues/10

**Comment by Keats** [comment]
I believe this can be closed @theduke?

**Comment by theduke** [comment]
@Keats sure.

I'll chime on in #10 some time today!
