### ISSUE TITLE
Required accepts an empty string "" as valid

### ISSUE THREAD

**Issue by simanacci** [Keats/validator#171]
```rust
#[derive(Debug, Deserialize, Validate)]
struct User {
    #[validate(required)]
    name: Option<String>,
}

async fn add_user(req: HttpRequest, form: web::Form<User>) -> HttpResponse {
    let answer = form.validate();
    println!("{:?}", form);
    println!("{:?}", answer);
    let opt: Option<String> = form.name.clone();
    let name = opt.unwrap();
    HttpResponse::Ok().body(format!("Added {}", name))
}
```
`User { name: Some(""), submit: "Submit" }`
`Ok(())`

**Comment by Keats** [comment]
That's normal, see https://github.com/Keats/validator#required

`""` is a value

**Comment by simanacci** [comment]
But isn't it a bit misleading, especially for HTML form input validation where you want to return a custom error message? A form with the <i>required</i> attribute will simply accept `""`.

**Comment by Keats** [comment]
Not really? All `required` does is check that there is a value. Whether that value is significant is up to the application. Very often an empty string would be a valid value.
Would 
```
    #[validate(required)]
    age: Option<u64>,
```
with age=0 be valid or invalid? What about `Option<Vec<String>>` and an empty vec?
