### ISSUE TITLE
How to validate field only when the field is not None or empty?

### ISSUE THREAD

**Issue by goldwind-ting** [Keats/validator#173]
```
#[derive(Debug, Validate, Deserialize)]
struct SignupData {
    #[validate(email)]
    mail: String,
    #[validate(phone)]
    phone: String,
    #[validate(url)]
    site: String,
    #[validate(length(min = 1), custom = "validate_unique_username")]
    #[serde(rename = "firstName")]
    first_name: String,
    #[validate(range(min = 18, max = 20))]
    age: u32,
}
```
For example, the validator only work when mail is not empty(""), if the mail is empty, the program still run correctly.

**Comment by Keats** [comment]
I do get `Err(ValidationErrors({"mail": Field([ValidationError { code: "email", message: None, params: {"value": String("")} }])}))
` if I try to validate this struct with an empty string?

**Comment by goldwind-ting** [comment]
I have resolved this, maybe could use Option(String), Option(u32)..... in above situation.
