### ISSUE TITLE
Allow validation of "string-like" types

### ISSUE THREAD

**Issue by cortopy** [Keats/validator#176]
I have code for protobuf messages generate with prost, which will be something like

```rust
struct Address {
  line1: prost::alloc::string::String
}
```

for most purposes `line1` is just a `String` and any function that works with one will work with the other.

However, because of the following function https://github.com/Keats/validator/blob/7e7ba65d7fef72b02fb9220c91abe8043ce37281/validator_derive/src/asserts.rs#L72

I can't use the derive annotations

Would it be acceptable to write the check as a match for "String"?

**Comment by loyd** [comment]
+ also for `CompactString` and other strings with SSO

**Comment by Keats** [comment]
This would be fixed by https://github.com/Keats/validator/issues/205
