### ISSUE TITLE
Expose `ValidationErrors.0` 

### ISSUE THREAD

**Issue by Nukesor** [Keats/validator#193]
Hi :)

First of all, thanks for creating and maintaining this project! It has been a huge help.

I'm currently trying to build a custom validator function. However, due to architectural limitations, that validation function cannot easily be called via the `Validate` trait, as the validation needs a database transaction which doesn't exist at this point in time yet.

Due to this, I'm currently planning to merge the validation from the original `Validate` trait with the validation errors from my custom function.

However, after looking through the docs, I couldn't find a way to access the `ValidationErrors.0` field directly.

My proposal would be to:

1. Simply make `ValidationErrors.0` public. This would allow users to hack around without adding a new obvious API  call.
2. Adding an `ValidationErrors::errors_mut(&mut self)`, which is the cleaner solution.

To give you some context of what I'm trying to do, here's a little bit of code:

```
let mut answer_errors = ValidationErrors::new();
for (index, answer) in questionnaire.answers.iter().enumerate() {
    // Ensure that all foreign keys exist.
    let result = validate_foreign_key_exists!(
        &mut *tx,
        "questions",
        "id",
        answer.question_id,
        "question_id"
    );

    if let Err(validation_errors) = result {
        // Register ValidationErrors based on the index in the actual answer list.
        let mut list_errors = BTreeMap::new()
        list_errors.insert(index, validation_errors);
        let error_map = answer_errors
            .errors_mut()
            .insert("answers", ValidationErrorsKind::List(list_errors))
    }
}
```

**Comment by Keats** [comment]
Isn't that `ValidationErrors::add` or `ValidationErrors::add_nested`?

**Comment by Nukesor** [comment]
- `add` panics on non Field entries
- `add_nested` would indeed indeed work for adding nested fields once, but it isn't publicly exposed.
     Also, this doesn't allow to add fields to an existing nested entry, as one has no possibility to get a mutable reference to the nested entry after it has been added.

**Comment by Keats** [comment]
Would adding `ValidationErrors::insert` be ok? `errors_mut` might be ok as well, just trying to see if it can be more narrow in scope

**Comment by Nukesor** [comment]
Understandable.

A combination of `insert` and `errors_mut` would definitely solve all problems.
`ValidationErrors::insert` would definitely be a nicer interface for adding new Nested/List error kinds. As far as I understand, this would be the same as `add_nested`?

`errors_mut` would be nice, but (for my current usecase) It would be sufficient, if one get's the possibility to have the possibility to add errors to nested fields/lists. This could look something like this:
    * The current `add_nested` is renamed to `insert` and exposed.
    * Add a new `add_to_struct(&mut self, field: &'static str, nested_field: &'static str, error: ValidationError)`, which adds an error to a ValidationErrorsKind::Struct
    * Add a new `add_to_list(&mut self, field: &'static str, index: usize, nested_field: &'static str, error: ValidationError)`, which adds an error to a `ValidationErrorsKind::List`

On second thought, these APIs seem rather verbose. They also don't allow to set values on multiple nested schemas, but only on the very first level.

I guess exposing the whole hashmap via `errors_mut` is probably the easiest way to solve all these problems in one go.

**Comment by Nukesor** [comment]
I guess another solution would be a combination of `add_to_struct`, `add_to_list` and `get_list_mut` and `get_struct_mut` to get recursive mutable access to all nested data structures.

**Comment by Keats** [comment]
Yeah, agreed on `errors_mut` seeing your examples
