### ISSUE TITLE
custom = path_of!(crate::xxx) is not execute

### ISSUE THREAD

**Issue by Silentdoer** [Keats/validator#198]
path_of! is a macro from ident_util, such as path_of!(crate::validate::validate_aaa) will generate a &'static str: "crate::validate::validate_aaa", it's benifit is that i can get tips from IDE when write a path

**Comment by Keats** [comment]
I have no idea of macros would interact with each others tbh

**Comment by IniterWorker** [comment]
@Silentdoer, 

For more help about this issue, you should re-format your issue and more information.
- Compiler errors
- Examples

Thanks
