### ISSUE TITLE
Use `Cow<'static, str>` instead of `String`

### ISSUE THREAD

**Issue by alexander-irbis** [Keats/validator#20]
Hi!

There is no point to allocate memory each time for a `String` value, much frequently we will need an `&'static str` value and only in rare cases we will need to allocate `String` for custom values.

for `validate`:
```rust
Result<(), HashMap<String, Vec<String>>>
```
=>
```rust
Result<(), HashMap<Cow<'static, str>, Vec<Cow<'static, str>>>>
```
or even
```rust
Result<(), HashMap<&'static str, Vec<Cow<'static, str>>>>
```

for custom validation functions respectively:
```rust
Option<Cow<'static, str>
```

**Comment by Keats** [comment]
The whole API is probably going to completely change with #10 but I haven't had the time/wanted to work on this project recently so it will take some time.

**Comment by Keats** [comment]
In 0.6.0
