### ISSUE TITLE
The required validator reports an error when passing the code and message attributes

### ISSUE THREAD

**Issue by bullub** [Keats/validator#200]

**Comment by Keats** [comment]
More details please?

**Comment by pintariching** [comment]
```
#[validate(required(message = "fill out this field or else...")}
pub name: Option<String>
```
I would like to change the default message for the required validator to translate it to my language.
This doesn't seem to work. I get an error: `unexpected list validator: "required"`.

**Comment by Keats** [comment]
If anyone has time to look at that, that would be great

**Comment by pintariching** [comment]
I would love to help out with this but I'm not sure where to start looking. I have to do some reading up on macros before I could help.

**Comment by Keats** [comment]
I think the first step is to add more tests to https://github.com/Keats/validator/tree/master/validator_derive_tests/tests

**Comment by pintariching** [comment]
I have added a new pull request #210. I'll experiment some more with it.
