### ISSUE TITLE
Use traits for validation rules

### ISSUE THREAD

**Issue by tqwewe** [Keats/validator#205]
When trying to derive `Validate` on a struct, it seems like the derive macro filters what types you can use manually.

Wouldn't it make more sense to instead have a trait for each validation rule, allowing users to implement validation rules for their custom types?

For example, this does not work:
```rust
#[derive(Validate)]
struct Data {
  #[validate(length(min = 5, message = "must have 5+ characters"))]
  name: Mutable<String>,
}
```

But I'd like to be able to do something like this to resolve it:
```rust
impl validator::rules::ValidateLength for Mutable<String> {
  fn validate_length(&self, min: Option<u64>, max: Option<u64>) -> Result<(), ValidationError> {
    // ...
  }
}
```

**Comment by Keats** [comment]
How would you the trait look like? I don't think it would work without variadic generics

**Comment by tqwewe** [comment]
I'm not sure why generics may be needed.
I was imagining something like:
```rust
trait ValidateLength {
  fn validate_length(&self, min: Option<u64>, max: Option<u64>) -> bool;
}

trait ValidateEmail {
  fn validate_email(&self) -> bool;
}

trait ValidateUrl {
  fn validate_url(&self) -> bool;
}

trait ValidateContains {
  fn validate_contains(&self, s: &str) -> bool;
}

...
```
And these traits would be implemented for some standard types where appropriate, eg `impl ValidateEmail for String`, etc.

**Comment by Keats** [comment]
Yeah my bad I was thinking the wrong thing yesterday. This would be nice but how do you envision it working in the proc macro? You still need to search for patterns in the fields types to know whether they are supported or try to di it anyway and get compilation errors in invisible generated code which isn't great.

**Comment by pintariching** [comment]
I have opened #225 to see if I'm going in the right direction. For now I've just implemented if for length`
