### ISSUE TITLE
New feature: NoneOf and OneOf

### ISSUE THREAD

**Issue by MilaKyr** [Keats/validator#207]
I would like to add two new validators. `one_of` and `none_of` that would work with fields, which implement `Iterator` trait and enums. 
Something like that:
```rust
enum Variants {
    A,
    B,
    C,
}

#[derive(Validate)]
struct MyStruct {
    #[validate(none_of(enum=Variant)]
    not_variant: String,
    #[validate(one_of(enum=Variant)]
    variant: String,
    ...
}
```

What do you think? Is it something useful from your point of view?

If so, I could start working on it :)

**Comment by Keats** [comment]
How would that work in practice?

**Comment by MilaKyr** [comment]
Don't know yet, but I can start working, and propose some ways how it can be done in practice.

Do you have any pointers or maybe thoughts regarding this idea?

**Comment by Keats** [comment]
Honestly that looks like it would be better as a custom serde deserializer than a validator, you're likely to want to convert `variant` to your actual enum rather than keeping it as a string.
