### ISSUE TITLE
Check length in email-validation

### ISSUE THREAD

**Issue by Glitchy-Tozier** [Keats/validator#209]
There seems to be a maximum to the allowed number of characters in an email.

According to my current understanding, doing regex-checks on very long email-addresses might be expensive. Checking the length before going to regex would be a faster way of detecting malicious email-strings & preventing DOS attacks.

In any case, doing an additional length-check would improve recognition of impossible emails.

A few links that might be helpful:
- https://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address#574698
- https://www.lifewire.com/is-email-address-length-limited-1171110
- https://blog.moonmail.io/what-is-the-maximum-length-of-a-valid-email-address-f712c6c4bc93

**Comment by Glitchy-Tozier** [comment]
I could probably implement this myself if the proposal is accepted

**Comment by pintariching** [comment]
I think you can just put all the validators you want in a list and use it like this: `#[validate(length(max = 100), email)]`

**Comment by Glitchy-Tozier** [comment]
That is a great idea, I'll do that for now!

However, since email-length seems to be predefined in some specification, it would make sense to have it automatically checked when validating an email. So I still stand by my suggestion :)

**Comment by pintariching** [comment]
That sounds like a good idea. We'll see what the maintainer thinks about this. So I guess it should check that everything before "@" isn't longer than 64 characters and everything after shouldn't be longer than 255 characters so in total no more than 320 characters?

<sub>Howevery anybody using emails this long should be shot  :P</sub>

**Comment by Keats** [comment]
That's probably be fine to add the email validator directly

**Comment by pintariching** [comment]
I opened the pull request #211 for this if anybody wants to check it out
