### ISSUE TITLE
Validating `Option::is_some`

### ISSUE THREAD

**Issue by kardeiz** [Keats/validator#21]
I haven't used your library yet, but it looks nice&mdash;

However, one of the primary validations I would want to perform on my structs would be `Option::is_some`, basically to check whether a builder-style struct is in a valid state.

It looks like the `custom` validator won't work here, since that is only run on the inner value in the `Option::Some` case.

I understand why you've designed it so validators are only run on options if `Option::is_some`, but it would be nice to have either an `is_some` validator or a custom validator that runs on the raw value.

**Comment by Keats** [comment]
Wouldn't it be solved by having your struct not have an option? the serialization would fail if the field is not there but you wouldn't get a nice error message.
A `required` validation could be added I guess?

**Comment by kardeiz** [comment]
@Keats thanks for the reply. I'm not sure what serialization has to do with this. I'm interested in using this library to validate a builder struct before transforming it to another struct, where the final struct has some conditions on the values (i.e. as supported by your crate). The builder struct may have some fields optional (to provide a nicer builder interface) even when they are not optional in the final struct.

**Comment by lucab** [comment]
As far as I understood, @kardeiz you would do it via [struct-level validation](https://github.com/Keats/validator#struct-level-validation) on the parent struct, checking for `is_some()` on a specific field of it.

**Comment by timvisee** [comment]
I think this can be closed, as #103 is implemented.
