### ISSUE TITLE
Validate string to not contain any spaces

### ISSUE THREAD

**Issue by stevenhansel** [Keats/validator#231]
I just noticed recently when testing my code, spaces inside string are not validated, I think this is a quite common use case in input validation. To be honest, I don't know if using `does_not_contain` and adding a blank space will work. So, I think it will be nice if we have another built-in attribute to validate if space exists or not, e.g. `no_space`.

P.S. I would like to contribute to this issue if this idea is approved

**Comment by Keats** [comment]
> I don't know if using does_not_contain and adding a blank space will work

That should work but you are not going to count all other types of whitespace and you should probably write your own validator function at that point - but I don't want to add more to this lib, i'd prefer to remove some tbh.

**Comment by stevenhansel** [comment]
I see, I think if that's the case, I will close this issue. Thanks!
