### ISSUE TITLE
Implement Validate for `Option<T: Validate>`

### ISSUE THREAD

**Issue by tsar-boomba** [Keats/validator#236]
Currently, option validation is done through the proc macro by checking if the type starts with `Option<` this is causing problems for me because I have to use the full path to option (`std::option::Option`) due to a bug in another crate. I may be missing something, but why not just do something like this:

```rs
impl<T: Validate> for Option<T> {
    pub fn validate(&self) -> Result<(), ValidateError> {
        if let Some(inner) = self {
            inner.validate()
        }
    }
}
```

Other than this we could check if someone is using the full path when doing option unwrapping in the proc macro. I'd be willing to do a pr for either, just checking to see what aligns with the goals of this crate the most.

**Comment by Keats** [comment]
Yes, we should move away from checking naively in the macro and let the compilation just fail imo.

**Comment by gzp-crey** [comment]
Any update on this ?
