### ISSUE TITLE
Implement the same behavior as Option

### ISSUE THREAD

**Issue by affanshahid** [Keats/validator#241]
I have a type which behaves the same as an `Option` in that it wraps another type which might or might not be there. It has some extra logic that is specific to my app. I want to give it the same behavior that an `Option` has i.e only validate if the value is there and pass on all validation settings to the wrapped type. How should I go about achieving this.

**Comment by biot023** [comment]
+1

**Comment by biot023** [comment]
(In my case it's the `MaybeUndefined<T>` from async_graphql `InputObject`.)
