### ISSUE TITLE
Doesn't generate

### ISSUE THREAD

**Issue by Sanjuvi** [Keats/validator#266]
Validator derive macro doesn't generate the code

**Comment by pintariching** [comment]
What crate version are you using? Can you give am example of the code that doesn't compile?

**Comment by tsmt09** [comment]
Did you miss feature `derive`? This fixed the issue for me

Cargo.toml:
`validator = { version = "0.16", features = ["derive"] }`

**Comment by Sanjuvi** [comment]
👍...solved
