### ISSUE TITLE
empty str can pass validator

### ISSUE THREAD

**Issue by MateSoftware2023** [Keats/validator#281]
"   " can pass -> length(min = 1)
any other validate fn supported , dont pass empty str

**Comment by omercotkd** [comment]
The string you provided is not empty you have a whitespace char, therefore his length is indeed one.
If the whitespace is not intentional provide a code example.
@MateSoftware2023

**Comment by MateSoftware2023** [comment]
thanks, 
i used custom validtor to solve this issue,
