### ISSUE TITLE
Error and Display are not implemented for validator::ValidationErrors

### ISSUE THREAD

**Issue by voidxnull** [Keats/validator#29]
Which makes it quite inconvenient and unintuitive to use the result of `Validate::validate` with the `?` operator. While a trivial implementation of `std::error:Error` would probably suffice, I'm not sure about the implementation of `std::fmt::Display`.

There also seems to be a mistake in README.md:
```rust
let errors = signup_data.validate()?;
```
According to https://github.com/Keats/validator/blob/1c0f14aaec42b772fa22861aba8c8b80fcda5b8a/validator/src/traits.rs#L81
`validate` doesn't return anything.

**Comment by Keats** [comment]
I've implemented the Error type for ValidationErrors locally but I think the main issue is that  `()` doesn't implement `Try` so you can't use `?` with a type like `Result<(), Whatever>` apparently.
I'm not sure what's the best course of action in this case, if it can't be used with `?` then there is no point for it to be a `Result`.

**Comment by e-matteson** [comment]
I ran into this too. I'd like to link ValidationErrors with error-chain, but that doesn't seem possible.

**Comment by Keats** [comment]
@e-matteson or @voidxnull 
Would you be able to do a PR? I couldn't think of a way to make it work cleanly last time

**Comment by voidxnull** [comment]
@Keats Ok, I'll try.

@e-matteson 
There is a workaround. Just define the error and implement `From` manually instead of using `foreign_links`:
```rust
error_chain! {
    errors {
        Validation(e: ::validator::ValidationErrors) {
            description("Validation error")
            display("Validation error") // or whatever
        }
    }
}

impl From<::validator::ValidationErrors> for Error {
    fn from(error: ::validator::ValidationErrors) -> Self {
        ErrorKind::Validation(error).into()
    }
}
```
