### ISSUE TITLE
Can't use static ref for Lazy<Regex>, how

### ISSUE THREAD

**Issue by headironc** [Keats/validator#297]
<img width="489" alt="Screenshot 2024-03-05 at 10 59 53" src="https://github.com/Keats/validator/assets/19648989/d61b2b13-3183-437c-a869-d2f5f39f032b">

<img width="809" alt="Screenshot 2024-03-05 at 11 01 25" src="https://github.com/Keats/validator/assets/19648989/da06dd1b-e8f2-43be-8166-eb34014fe3ea">

**Comment by attila-lin** [comment]
`ref` is unnecessary.

**Comment by headironc** [comment]
<img width="783" alt="Screenshot 2024-03-05 at 21 43 21" src="https://github.com/Keats/validator/assets/19648989/13e9a591-6e8c-4e95-8edd-47eb16abc658">
<img width="1165" alt="Screenshot 2024-03-05 at 21 43 28" src="https://github.com/Keats/validator/assets/19648989/a9dcb7d1-a10c-4e65-8347-d4b772adf3aa">

After upgrade this crate, this happened
