### ISSUE TITLE
Add struct level validation

### ISSUE THREAD

**Issue by Keats** [Keats/validator#3]
Sometimes fields can ok individually but might be invalid when looking at the whole thing, for example 2 fields are optional but at least one of them has to be there

Allowing a custom function on the struct itself is necessary

**Comment by jacob-pro** [comment]
Was any progress made on this issue or is it possible to re-open it?

I have the following use case:

```
#[derive(Validate)]
pub struct Outer {
   #[validate(length(min = 4))]
   pub other: String,
    #[validate(custom = "validate_inner")]
    pub inner: Inner,
}

#[derive(Validate)]
pub struct Inner {
    pub interval: u8,
    pub timeout: u8,
   #[validate(length(min = 4))]
   pub other: String,
}

fn validate_inner(inner: &Inner) -> Result<(), ValidationError> {
    if inner.timeout >= inner.interval {
        return Err(ValidationError::new("Timeout must be less than the run interval"));
    }
    Ok(())
}
```

I would like to validate the `Inner` struct to ensure that one field value is larger than the other. But if I add a custom validator, I then lose the ability to validate the rest of the `Inner` struct - even if I can call `inner.validate()` inside the custom function the return types would not fit.

**Comment by Keats** [comment]
Yep, it's in the library: https://github.com/Keats/validator#struct-level-validation

**Comment by jacob-pro** [comment]
Thank you @Keats! 

Sorry I managed to miss that in the docs (I had tried just tried using `#[validate(function = "validate_runner_setting")]` which of course didn't work!)
