### ISSUE TITLE
phone feature is missing in new version

### ISSUE THREAD

**Issue by sam-rusty** [Keats/validator#302]
I am trying to update my app to use 0.17.0, but looks like phone feature is no longer available. what is the alternative?

**Comment by Keats** [comment]
You can use the crate we were using directly and write a custom validator using it

**Comment by vinicius73** [comment]
@Keats is it intentional? or there plans to solve it?

**Comment by Keats** [comment]
It was intentional yes. It's better to write a custom validator for the kind of phone number you want to accept than adding the options to the validator
