### ISSUE TITLE
Validation of nested structs?

### ISSUE THREAD

**Issue by e-matteson** [Keats/validator#31]
Let's say I'm deserializing to a parent struct whose fields are other structs, which implement Validate. I hoped that if I called `validate()` on the parent, it would automatically call `validate()` on its nested structs. But this code prints out "validated!", even though Bar is invalid: 

```
#[macro_use]
extern crate serde_derive;
extern crate toml;
#[macro_use]
extern crate validator_derive;
extern crate validator;

use validator::{Validate};

#[derive(Deserialize, Debug, Validate)]
struct Foo {
    bar: Bar,
}

#[derive(Deserialize, Debug, Validate)]
struct Bar {
    #[validate(range(min = "0", max = "9"))]
    y: i32
}

fn main() {
    let foo: Foo = toml::from_str(r#"
    [bar]
    y = -1
    "#).unwrap();

    match foo.validate() {
        Ok(_) => println!("validated!"),
        Err(e) => println!("{:?}", e),
    };
}
```  

I can't figure out a  good way to explicitly call `validate()` on the nested struct, either. I tried adding a `#[validate(custom("Bar::validate"))]` attribute to the `bar` field, but that resulted in `error: proc-macro derive panicked`. 

Is there any better way to validate nested structs than to implement my own method for Foo that manually calls `validate()` on every field?

**Comment by Keats** [comment]
I have to say I didn't think of nested structs at all :(

I guess we can modify the proc macro to check if there is a `Validate` tag but that doesn't really work in terms of types for the errors: right now it's a hashmap string -> Vec<Error> but for nested structs we would want hashmap -> (hashmap -> Vec<Error>) to represent errors on various fields. Not sure what's the best plan for that, maybe have an enum to represent the kind of error?
Reference: http://marshmallow.readthedocs.io/en/latest/nesting.html

**Comment by greglearns** [comment]
Could you continue to use hashmap -> Vec if you treated each string key as a "path.to.each.nested.object", so that you could have "top.number" -> "is invalid" and "top.address.street" -> "is missing a street number" or something like that?

**Comment by Keats** [comment]
It would work but it would be a pain to iterate through the errors in the frontend as you would need to check what the field name starts with. Not a proper solution imo

**Comment by Keats** [comment]
If anyone wants to try it before I release a new version, they can use the crates from the `master` branch. Release will probably happen early next week, I want to play with it a bit as well.

**Comment by simonsparks** [comment]
:tada:
