### ISSUE TITLE
Get rid of `proc-macro-error` (RUSTSEC-2024-0370 and `syn` version)

### ISSUE THREAD

**Issue by domenicquirl** [Keats/validator#351]
So, someone filed [an advisory](https://rustsec.org/advisories/RUSTSEC-2024-0370) against `proc-macro-error` for being unmaintained. Since `validator-derive` uses it, using `validator` made this show up in our CI. Tbh I'm somewhat sceptical as to the proposed solution of migrating to [`proc-macro-error-2`](https://crates.io/crates/proc-macro-error2), both because it is _very_ recent and already had to release a bugfix for an oversight they made when forking the project, and because the primary reason to use `proc-macro-error` at all (to me, at least) is because it abstracts over stable vs. nightly diagnostic capabilities for proc macros, which the sequel _doesn't do_ - they use a feature flag instead that needs to be set by the dependent.

That said, the original `proc-macro-error` due to its age is also one of the few crates in our dependency graph to still depend on `syn` version 1. Having to compile `syn` twice in an early stage of the build (since it is needed for basically all proc macros) is not great, and might honestly be a better / bigger reason to stop using `proc-macro-error`. As an alternative to switching to `proc-macro-error2`, here's a recent [PR in `utoipa`](https://github.com/juhaku/utoipa/pull/920) (in particular the `Diagnostics` bit [here](https://github.com/juhaku/utoipa/pull/920/files#diff-47e72141b16628e12c96b0ceaaa964505a98380f2a9baba8c0c5f696be63d749R3022), which GitHub likes to collapse by default). It's a bigger PR, but their macro API surface is also very large, so it should be less effort to do for `validator-derive` if that is wanted.

**Comment by domenicquirl** [comment]
There is also [`proc-macro2-diagnostics`](https://crates.io/crates/proc-macro2-diagnostics) which is maintained and provides the same functionality (namely the nightly detection) of `proc-macro-error`.

**Comment by pvichivanives** [comment]
Update on this in case anyone is following: PR has been merged, awaiting new version release though.

**Comment by timleslie** [comment]
Just to set expectations, is there an ETA on a release? We have a low-urgency ticket to resolve the RUSTSEC issue in our repo, so it would be helpful if I could update that with a timeframe.

Thanks for all the work that goes into maintaining this crate, it's much appreciated 🙏

**Comment by Keats** [comment]
Probably next week when i get back from holiday
