### ISSUE TITLE
Email validation does not handle this case

### ISSUE THREAD

**Issue by Edgar200021** [Keats/validator#352]
![2024-10-13-100400_hyprshot](https://github.com/user-attachments/assets/58224fef-eb30-47f4-b9e8-058a10ae9332)
![2024-10-13-100345_hyprshot](https://github.com/user-attachments/assets/dd0a99a5-2b8e-4b1a-bab9-2c80402994bf)
![2024-10-13-100335_hyprshot](https://github.com/user-attachments/assets/3ec2d428-7828-4ed7-8d19-4921d08c6b63)

**Comment by Keats** [comment]
See  https://github.com/Keats/validator/issues/349

It can be a valid email
