### ISSUE TITLE
Does not work on Option<Option<T>>

### ISSUE THREAD

**Issue by csharad** [Keats/validator#41]
Though validation works on `Option<T>`, it would be beneficial if the same logic would work on `Option<Option<T>>`. 
To communicate with the JS world with `null`, `undefined` & `T`, I need to use `Option<Option<T>>`. And to validate it, currently I am using custom validation. 
So, this is a feature request to make it built-in.

**Comment by Keats** [comment]
Is `Option<Option<T>>` used by other wasm frameworks? I had a look but couldn't find it in `stdweb` or `yew`, I'm probably looking in the wrong places though

**Comment by csharad** [comment]
Sorry for the late reply.
I didn't completely explain the problem. What I mean is when writing the Frontend app in JS, we get values that may be `null` or `undefined` or `T`.  To handle those possible values in Rust server, I need to use `Option<Option<T>>` which can't be validated currently.
So how can I handle such a use case?

**Comment by Keats** [comment]
Sorry forgot to reply. Now that `syn` and `quote` have been updated, I'd welcome a PR for that but don't think I'll implement it myself.
