### ISSUE TITLE
string length validation not working as expected

### ISSUE THREAD

**Issue by Dowwie** [Keats/validator#48]
Why does this work?  I am using validator = "0.6.3" and validator_derive = "0.6.5", rustc stable 1.25

```rust

#[derive(Validate)]
struct Something {
    field_a: String,
    #[validate(length(min = "1", max = "10"))]
    field_b: String
}

fn main() {
    let something = Something {field_a: "hello".to_string(),
                               field_b: "helloooooooooooooooooooooooooooo".to_string()};
}
```

**Comment by Keats** [comment]
Did you forget to call the validation in your example? The main only has the struct instantiation

**Comment by Dowwie** [comment]
Aha.  I did *not* know that I had to manually call a validate method.  Thanks!
