### ISSUE TITLE
can we feature gate the card validator?

### ISSUE THREAD

**Issue by barzamin** [Keats/validator#49]
i'd prefer not to pull in the `card-validate` dependency; i don't need it at all for 99% of the things i use this lib for.

**Comment by Keats** [comment]
Isn't it already feature-gated by the `phone` feature?

**Comment by barzamin** [comment]
@Keats [no](https://github.com/Keats/validator/blob/master/validator/Cargo.toml#L23).

**Comment by Keats** [comment]
@barzamin Any chance you can do a PR for that? The intent was to feature gate it so it's a bug

**Comment by barzamin** [comment]
Will do.
