### ISSUE TITLE
Support using validators without attr_literals feature

### ISSUE THREAD

**Issue by dtolnay** [Keats/validator#5]
Obvious follow-up to https://github.com/Keats/validator/issues/4 I guess.

I know this is more user-friendly: `#[validate(range(min = 18, max = 20))]`

But would it be possible to support this as well? `#[validate(range(min = "18", max = "20"))]`

And similar for the other validators. This would allow validators to be used on stable Rust 1.15.

It looks like this may be as simple as just extending the `lit_to_int` and `lit_to_float` functions to handle string literals.

**Comment by Keats** [comment]
Yeah, that's the easy solution I think

**Comment by Keats** [comment]
Tooks lots of time but it's in 0.2.0 (along with struct level validation)
