### ISSUE TITLE
export validator_derive from validator

### ISSUE THREAD

**Issue by mmrath** [Keats/validator#58]
Can we do something like the failure crate? This would be a bit more ergonomic to use the lib.

**Comment by Keats** [comment]
How do they do it? I thought it wasn't possible to export a custom derive with other things

**Comment by mmrath** [comment]
Some details here.
https://users.rust-lang.org/t/solved-is-it-possible-to-reexport-a-proc-macro/16864/6

I think they just reexport the macros.

**Comment by Keats** [comment]
I am not sure if it's possible in our case as we use `validator` in `validator_derive`

**Comment by Keats** [comment]
To add more details: I've tried it but you get an error for an import loop.
If anyone has a fix for that, I'd love that to happen.

**Comment by theduke** [comment]
I'm doing the same thing in [juniper_codegen](https://github.com/graphql-rust/juniper/blob/master/juniper_codegen/src/lib.rs).

Sadly, there's not a good solution for this. My solution is to have an additional , hidden internal version of the macro, eg `Validate` and `ValidateInternal`. 

Then, during code generation, you have something like:

```rust
let crate_name = if is_internal { quote!( crate ) } else { quote!( validator ) };
...
quote!( 
  impl $crate_name::Validate for _ { ... }
```

And inside `validator`, you would use the `ValidateInternal` derive instead. 

It's a bit hacky, but it works.
