### ISSUE TITLE
example of parameterized testing of validation rules

### ISSUE THREAD

**Issue by Dowwie** [Keats/validator#63]
Hey, I put together a small example of how to use macros to conduct parameterized testing, with an example using the validator crate.  Would you like to add this to the validator project?  https://github.com/Dowwie/parameterized_testing

If so, it's yours

**Comment by Keats** [comment]
Correct me if I'm wrong but I think we can link to `validator_derive/tests/complex.rs` for examples, although we should probably have an examples folder in the repo once the next version is released.
