### ISSUE TITLE
Option<String> doesn't work

### ISSUE THREAD

**Issue by Boscop** [Keats/validator#64]
Why doesn't `Option<String>` work? Shouldn't it work in v0.6.3?

![image](https://user-images.githubusercontent.com/535593/46321448-a3229200-c5e3-11e8-99e3-faffc95fbfc5.png)

```rust
#[validate(regex = "RE_TIME")]
automatic_closing_time: Option<String>,
```

**Comment by Keats** [comment]
Hmm should work, do you have the issue in 0.8 still?

**Comment by Keats** [comment]
There are many tests with `Option<String>` so likely not a problem anymore
