### ISSUE TITLE
Could ValidationErrors::field_errors() take &self instead of self?

### ISSUE THREAD

**Issue by philbooth** [Keats/validator#65]
Hey, I was wondering what the reason for making `field_errors()` take `self` was?

I have [some code](https://github.com/mozilla-services/syncstorage-rs/pull/70/files#diff-2c5b3fa267b18e8f400e96cc130d0f70R150) that needs to call it on a borrowed `ValidationErrors` instance, and have resorted to doing an explicit `clone()` beforehand. But it seems like it would work just as well if it took `&self` instead. Am I missing something / would you consider a change to the API?

**Comment by Keats** [comment]
I *think* `errors` and `field_errors` could take `&self`. @simonsparks any reasons in particular they take `self`?

**Comment by simonsparks** [comment]
I think this could be a leftover from an earlier approach to nested validation, where errors were merged into a single `ValidationErrors` instance. The approach that was accepted ended up not doing this merge though so, yes, I expect `field_errors()` could take `&self`.

**Comment by Keats** [comment]
Cool, I'll change it in the next major release then.
