### ISSUE TITLE
Allow range validator to refer to a variable

### ISSUE THREAD

**Issue by bbangert** [Keats/validator#66]
The range validator requires the raw numerical value in quotes. It should let it be a variable name in scope as well (or instead).

**Comment by mehcode** [comment]
I'd love this. Perhaps:

```rust
struct Foo {
    #[validate(range(min = "1", max = "{order_amount_max}"))]
    amount_min: i32,

    #[validate(range(min = "{order_amount_min}"))]
    amount_max: i32,
}
```

It might be nice to have `gt`, `lt`, `lte`, and `gte` validators as well

**Comment by Keats** [comment]
The next version will use Rust 1.30 so numbers will be literal and if it's a string, it's safe to assume it is a variable.
You can already do `gt`, `lt`, `lte`, `gte` manually with the range validator so I don't think it makes sense to add it.

I need to find some time to upgrade the code to use literals and then I will take a PR for the variable bit

**Comment by mehcode** [comment]
From the docs its not clear that you can just do `min = ..` in the range validator (and leave out the `max`).  I even wrote that as an example thinking that its not possible but it'd be nice but I guess it is.

**Comment by xFrednet** [comment]
I think this issue can be closed :)
