### ISSUE TITLE
validation for CLI

### ISSUE THREAD

**Issue by flip111** [Keats/validator#67]
Would be nice if there where some validators to usual command line input. The most basic ones would be to check if a file or directory exist or a glob pattern matches anything. Maybe also some validators to do something with networking (url's). Don't know what else would be useful for cli

**Comment by Keats** [comment]
it feels like something you would do at the struct level validation because the CLI validation bits you mention are not really in the scope of that crate

**Comment by Keats** [comment]
Closing; not really in the scope for that project.
