### ISSUE TITLE
Suggestion: Actix integration that validates directly from the request? (behind a feature flag of course)

### ISSUE THREAD

**Issue by mehcode** [Keats/validator#68]
```rust
#[derive(Deserialize, Validate)]
pub struct Foo {
  #[validate(range(min = "10", max = "100"))]
  bar: u32,
}

fn index(body: Validated<Json<Foo>>) {  ... }
```

---

`Validated` would be a `pub struct Validated<T>(T)` wrapper struct that implements `actix_web::FromRequest` and returns a `422` on validation errors with a nice response body describing errors.

---

If this is something you feel should be included I'd love to contribute a PR here.

**Comment by Keats** [comment]
Can't this be added outside of the repo? Like in a `actix-validator`?

**Comment by mehcode** [comment]
That's fair. I guess I'm used to crates like `diesel` having feature flags to enable support for chrono, uuid, etc. Though I remember that's a limitation of Rust's coherence rules which I _think_ is being fixed in a recent RFC.

That said, yeah, I'll probably package that up in a `actix-web-validator` crate.

**Comment by sekoyo** [comment]
I'm new to Rust, would be nice if there was an example of spitting out a nice Json response on this repo. Can you share @mehcode
