### ISSUE TITLE
Allow range validator to only have 1 argument

### ISSUE THREAD

**Issue by mehcode** [Keats/validator#69]
I'm trying to have just a "greater than" validation (must be `>` than `0`).

```rust
#[validate(range(min = "1"))]
```

Fails with

```
Validator `range` requires 2 arguments: `min` and `max`
```

**Comment by Keats** [comment]
It does look like my memory was wrong, I thought it was possible :(
I am not against the idea but how to define what are the min/max values? Should it use the Rust defaults like `u8::MIN`, `u8::MAX` for each type?

**Comment by PeteJodo** [comment]
could the `min` and `max` fields in `Validator::Range` just be `Option<f64>` and then check only what needs to be checked in the `validate_range` function? You could then have `validator_derive` fail if both are not set. Also irrelevant, but why `f64` and are there any implications with `f64`?
