### ISSUE TITLE
Is there any validator to check the value is not the data types' default zero value?

### ISSUE THREAD

**Issue by dumindu** [Keats/validator#75]
Hi,

Is there a validator similar to [Go's validator.v9 Required](https://godoc.org/gopkg.in/go-playground/validator.v9#hdr-Required), which validates the value is not the data types' default zero value? 

Thanks

**Comment by Keats** [comment]
There are no zero values in Rust and the Go approach causes bugs (0 can be a totally valid value). Use `Option` if there are no values

**Comment by dumindu** [comment]
Hi,
Thanks for the quick response. In my case I need to validate
- floats except 0
- floats >0

So, I need to use min max validators for this type of cases?

**Comment by Keats** [comment]
Yep use min/max

**Comment by dumindu** [comment]
@Keats Is there any way to use only min or max without using range?

**Comment by Keats** [comment]
It's coming in the next version
