### ISSUE TITLE
Make derive a feature

### ISSUE THREAD

**Issue by jannschu** [Keats/validator#78]
I suggest to handle the derive macro like serde and create a "derive" feature. Then only

```rust
use validator::Validate;
```

is needed.

Edit: I am not sure if  #58 is related.

**Comment by Keats** [comment]
It is related but I don't think it's doable for the reasons mentioned in #58 
If someone manages to do it without doing too many shenanigans, I'll take it

**Comment by Keats** [comment]
It's done!
