### ISSUE TITLE
Validation stops at parent

### ISSUE THREAD

**Issue by jamessewell** [Keats/validator#81]
If I have the following:

```rust
pub struct Polygon {
    #[validate]
    #[validate(length(min=3, max=1000, message="INVALID_TARGET", code="Polygon is constructed of less than 3 or more than 1000 points"))]
    vertices: Vec<Coordinates>,
}

pub struct Coordinates {
    #[validate(custom(message="INVALID_TARGET", function="easting_validator"))]
    easting: f32,
   #[validate(custom(message="INVALID_TARGET", function="northing_validator"))]
    northing: f32,
}
```

And the validation on `vertices` fails then I do not get validation errors on `easting` or `northing`. 

Is there a way to get both in one response?

**Comment by Keats** [comment]
> Is there a way to get both in one response?

I will need to check the code but I'm 90% sure there is no way

**Comment by Keats** [comment]
Actually it looks like it should merge the validations. You can try to expand the generated code with cargo-expand to see what is the code generated for that.
