### ISSUE TITLE
negative number in range

### ISSUE THREAD

**Issue by jamessewell** [Keats/validator#82]
This:

```rust
#[validate(range(min=-90, max=90))]
northing: f32,
```

Doesn't work:

```
error: proc-macro derive panicked
 --> src/model/geospatial.rs:9:41
  |
9 | #[derive(Debug, Serialize, Deserialize, Validate)]
  |                                         ^^^^^^^^
  |
  = help: message: internal error: entered unreachable code: Got something other than a list of attributes while checking field `northing`
```

Should this be supported?

**Comment by Keats** [comment]
Seems like a valid thing to add!

**Comment by haruntuncay** [comment]
Hello @Keats, I was planning on helping this project by handling this issue but there doens't seem to be a problem with negative range parameters. Could you please confirm its fix or this issue's current state ? Thanks in advance.

**Comment by Keats** [comment]
It might be fixed now, if you can add some tests for negative numbers in a PR and we can see.

**Comment by haruntuncay** [comment]
I actually tried it in my computer and I was able to apply negative ranges without any problems. Could you also confirm and if no problems arise, close the issue ?

**Comment by Keats** [comment]
Yep, looks like it works.
