### ISSUE TITLE
Can you please increase dependencies version in Cargo.toml

### ISSUE THREAD

**Issue by incker** [Keats/validator#86]
Can you please increase dependencies version in Cargo.toml

validator:

    url = "1"  →  url = "2"
    idna = "0.1"  →  idna = "0.2"
    card-validate = "2.1"  →  card-validate = "2.2"
    + phonenumber

validator_derive:

    syn = "0.15" →  syn = "1"
    quote = "0.6" →  quote = "1"
    proc-macro2 = "0.4" →  proc-macro2 = "1"

Forward thank you!

**Comment by Keats** [comment]
It's released as 0.10
