### ISSUE TITLE
Any plans for password validation?

### ISSUE THREAD

**Issue by c0dearm** [Keats/validator#88]
Thank you very much for your work, I plan to use this crate to do some validation of some data coming from REST requests.

I think it would be nice to support password validation too. I.e. checking it has the minimum required strength (lower case and upper case, symbols, minimum length...). 

Are there any plans for it? If so I could try to implement it myself.

**Comment by Keats** [comment]
Since password rules differ from site to site, it's better for a user to just define a custom validation function.
