### ISSUE TITLE
Add examples with message and code attibutes to the README.md

### ISSUE THREAD

**Issue by xFrednet** [Keats/validator#99]
I wanted to add a message to a regex validation using a macro. Sadly, I had to look into the tests to find an example how to do this. It would be nice to add examples like:

```Rust
#[validate(regex(path="USERNAMES_RE", message="invalid_username"))]
```

The same would be useful for custom validation. :)

I would volunteer to add a couple of examples, however I wanted to get your opinion first :)

**Comment by Keats** [comment]
Go for it!

**Comment by xFrednet** [comment]
Awesome! 

Do you know if there is any way to add a message or code attribute to a nested validate? @Keats
